language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-26
before_install:
  openssl aes-256-cbc -K $encrypted_255c9f433d16_key -iv $encrypted_255c9f433d16_iv -in me-cpele-android-keystore.jks.enc -out me-cpele-android-keystore.jks -d
script:
  ./generate-signed-apk.sh