language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-26
before_install:
- openssl aes-256-cbc -K $encrypted_255c9f433d16_key -iv $encrypted_255c9f433d16_iv
  -in google-play-android-dev.p12.enc -out secure/google-play-android-dev.p12 -d
- openssl aes-256-cbc -K $encrypted_255c9f433d16_key -iv $encrypted_255c9f433d16_iv
  -in secure/me-cpele-android-keystore.jks.enc -out secure/me-cpele-android-keystore.jks
  -d
script: "./generate-signed-apk.sh"
