language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-26
before_install: openssl aes-256-cbc -K $encrypted_255c9f433d16_key -iv $encrypted_255c9f433d16_iv
  -in me-cpele-android-keystore.jks.enc -out me-cpele-android-keystore.jks -d
script: "./generate-signed-apk.sh"
deploy:
  provider: releases
  api_key:
    secure: YxZYGQo86EgUsKRGu7Q4U+T/fHbnkBkKLP9e/GeXHgwULABA3nhz/huaYQmo6erobl5cBOrEY7QZ6Njwrm5gw3xfOiklZBwzfcjzFBjDu+UKWHHMW1RCar6/S1s+XiDVN1N8IBdH7blnixIQJgpSZICql2VBLfh0BcAAtLMj/Ha/uoJAssiSXtDfjZUgSJ3+FcuJgLlZ+6EPIfdzpt7k//tptMOqHuzYdXtSPSifq0EICWD3cCneuvCEoddFczJ3xmWb+PD6ra7JLrVEC0XGQ8YYRiU7cMk7wVgqlx7JScdXeSayflmhOvreB9PAW6/Te5MYUMui7DCLETvhpb4f/1Me8raFig2Fa9gLPnilLOmgsy3Q8eVSYU7hMrcWWdPvXF4PaGS65XKeWhzWXSuqa0sMRD7txJo0gWEyIC0C7fZfxbtLNkUWBCAV4GgVZdCE3H1ZoT84KyULNckiK9Y5O+TuBc/i49GlCY1H4lGFXiv3bG84f6NnmCDlO/oZT36JGvzJPgFu+FTnzOafZrhE5l8mbvNFosUcsNCwX3Kpr+Zdnu8jJ0XnZxpVBk3FAkfzw7+6cCDvvPjewAblAY7Q/xy+5H9OdO7NvuEx5TRD+CXuMxCbiZHAzs0cC4qupelcXfnpimjh+HdLWjzU4q1SoQyA5POeQ2v67k5oU9SQ5GU=
  file: app/build/outputs/apk/production/release/app-production-release.apk
  skip_cleanup: true
  on:
    repo: geekarist/inbop
    branch: develop
